baseURL = "https://blog.tusharmishra.in/"
languageCode = "en-us"
title = "Open Source Fever"
theme = "hugo-nederburg-theme"
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

summaryLength = 40

[params.social]
  email         = "tusharm@gmail.com"
  github        = "https://github.com/tmess567"